services:
  # Redis for caching and Celery broker
  redis:
    container_name: reservation-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  # Mailhog for email testing
  mailhog:
    container_name: reservation-mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - app-network

  # Prometheus for metrics
  prometheus:
    container_name: reservation-prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  # Grafana for visualization
  grafana:
    container_name: reservation-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    depends_on:
      - prometheus
    networks:
      - app-network

  # PostgreSQL database
  postgres:
    container_name: reservation-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # pgAdmin for database management
  pgadmin:
    container_name: reservation-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - app-network

  # FastAPI application
  app:
    container_name: reservation-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"  # Metrics port
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - FROM_EMAIL=${FROM_EMAIL}
      - METRICS_PORT=8001
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - app-network

  # Celery worker
  celery_worker:
    container_name: reservation-celery-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - FROM_EMAIL=${FROM_EMAIL}
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  # Celery Flower for monitoring
  flower:
    container_name: reservation-celery-flower
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: celery -A app.worker flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
      - celery_worker
    networks:
      - app-network

  # Sentry for error tracking
  sentry:
    container_name: reservation-sentry
    image: getsentry/sentry:latest
    ports:
      - "9000:9000"
    environment:
      - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
      - SENTRY_POSTGRES_HOST=${SENTRY_POSTGRES_HOST}
      - SENTRY_DB_USER=${SENTRY_DB_USER}
      - SENTRY_DB_PASSWORD=${SENTRY_DB_PASSWORD}
      - SENTRY_DB_NAME=${SENTRY_DB_NAME}
      - SENTRY_REDIS_HOST=${SENTRY_REDIS_HOST}
    depends_on:
      - postgres
      - redis
    volumes:
      - sentry_data:/var/lib/sentry/files
    networks:
      - app-network

  # OpenTelemetry Collector
  otel-collector:
    container_name: reservation-otel-collector
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter
    networks:
      - app-network

  # RabbitMQ for message queue
  rabbitmq:
    container_name: reservation-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  # Setup test database
  setup_test_db:
    container_name: reservation-setup-test-db
    image: postgres:15-alpine
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to be ready...';
        while ! pg_isready -h postgres -p 5432 -U ${POSTGRES_USER}; do
          sleep 1;
        done;
        echo 'Creating test database...';
        psql -h postgres -U ${POSTGRES_USER} -d postgres -c 'CREATE DATABASE reservations_test;';
        echo 'Test database setup complete!';
      "
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  redis_data:
  prometheus_data:
  grafana_data:
  postgres_data:
  sentry_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge 