global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'celery'
    static_configs:
      - targets: ['celery_worker:8000']

  - job_name: 'locust'
    static_configs:
      - targets: ['locust:8089']
    metrics_path: '/metrics'
    scheme: 'http' 