global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['reservation-api:8000']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 5s

  - job_name: 'celery'
    static_configs:
      - targets: ['reservation-celery-worker:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'locust-master'
    static_configs:
      - targets: ['reservation-locust:8001']

  - job_name: 'locust-worker'
    static_configs:
      - targets: ['reservation-locust-worker:8001']
    metrics_path: '/metrics'
    scheme: 'http' 